// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/**
 * @title Simple Escrow Contract (Inline Yul edition)
 * @notice Same escrow semantics as the original Solidity version, but the
 *         checks, storage access, and external calls are written as inline
 *         Yul (`assembly { ... }` blocks) instead of plain Solidity.
 *
 * Notes on what stays outside assembly, and why:
 * - `immutable` variables (depositor, beneficiary, arbiter) can be READ from
 *   assembly, but Solidity does not allow ASSIGNING immutables from inside
 *   assembly. So the one-time constructor assignment stays as plain
 *   Solidity; everything else that reads/uses them is done in Yul.
 * - `emit` cannot be issued from assembly directly, so events are emitted
 *   with a raw `log` opcode call inside assembly instead of `emit`, which
 *   keeps the *entire* event emission in Yul too (see below).
 * - Custom errors replace require-strings, since revert reasons are cheaper
 *   and easier to encode by hand in Yul (4-byte selector, no string ABI
 *   encoding needed).
 *
 * Selector reference (computed via keccak256, first 4 bytes):
 // The numbers generated here are Keccak256 hashes. These are calculated using Keccak256 and match the same ones calculated 
 // in the abi when the contract is compiled. When:
    mstore("memory location", "Location of error ZeroAddress() in abi(1st 4 bytes)")

 if iszero(_beneficiary) {
                mstore(0x00, 0xd92e233d00000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }

    selector = first 4 bytes of keccack256("ZeroAddress()")
    solc(Solidity Compiler) computes this same hash independently when builing the AbI, so this hardcoded value matches the ABI entry
    for ZeroAddress(). No link is enforced by the compiler - it only matches because the signature string here is identical to the solidity
    declaration. When revert is called, revert(0x00, 0x04), it returns the 1st 4 bytes of the signature at 0x00, which matches the ABI's 
    signature for ZeroAddress()

 *   ZeroAddress()      -> 0xd92e233d
 *   ZeroDeposit()      -> 0x56316e87
 *   NotArbiter()       -> 0xccb665a6
 *   AlreadyResolved()  -> 0x6d5703c2
 *   NoFunds()          -> 0x43f9e110
 *   TransferFailed()   -> 0x90b8ec18
 *
 * Event topic0 reference (keccak256 of the event signature):
 *   Approved(uint256) -> 0x3ad93af63cb7967b23e4fb500b7d7d28b07516325dcf341f88bebf959d82c1cb
 *   Refunded(uint256) -> 0x3d2a04f53164bedf9a8a46353305d6b2d2261410406df3b41f99ce6489dc003c
 *
 * isApproved is a single bool in storage slot 0.
 */
contract Escrow {
    address public immutable depositor;
    address public immutable beneficiary;
    address public immutable arbiter;

    // Storage slot 0. Declared normally so public getter/ABI metadata is
    // still generated by the compiler; all reads/writes happen via sload/sstore.
    bool public isApproved;

    event Approved(uint256 amount);
    event Refunded(uint256 amount);

    error ZeroAddress();
    error ZeroDeposit();
    error NotArbiter();
    error AlreadyResolved();
    error NoFunds();
    error TransferFailed();

    /**
     * @notice Sets up the escrow with a one-time deposit.
     * @dev Immutable assignment must stay in plain Solidity (see notes
     *      above); the validation of inputs is done in Yul.
     */
    constructor(address _beneficiary, address _arbiter) payable {
        assembly {
            // require(_beneficiary != address(0), "Beneficiary cannot be zero address");
            if iszero(_beneficiary) {
                mstore(0x00, 0xd92e233d00000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }
            // require(_arbiter != address(0), "Arbiter cannot be zero address");
            if iszero(_arbiter) {
                mstore(0x00, 0xd92e233d00000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }
            // require(msg.value > 0, "Must deposit some Ether");
            if iszero(callvalue()) {
                mstore(0x00, 0x56316e8700000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }
        }

        depositor = msg.sender;
        beneficiary = _beneficiary;
        arbiter = _arbiter;
    }

    /**
     * @notice Arbiter approves release of all funds to the beneficiary.
     * @dev Checks-Effects-Interactions, all in Yul:
     *      1. Checks: caller is arbiter, not already resolved.
     *      2. Effects: isApproved = true (sstore) BEFORE the external call.
     *      3. Interaction: raw `call` with the full balance, result checked.
     *      4. Log: manual `log2` emitting the Approved(uint256) event.
     */
    function approve() external {
        // Cache immutable into a local so assembly can read it (assembly
        // may read immutables, but only via a variable already in scope).
        address _arbiter = arbiter;

        assembly {
            // onlyArbiter modifier, inlined:
            if iszero(eq(caller(), _arbiter)) {
                mstore(0x00, 0xccb665a600000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }
            if sload(0) {
                mstore(0x00, 0x6d5703c200000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }

            // Effect: mark resolved first.
            sstore(0, 1)

            // balance = address(this).balance
            let bal := selfbalance()
            if iszero(bal) {
                mstore(0x00, 0x43f9e11000000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }
        }

        // beneficiary is immutable, cache it too for the assembly block below.
        address _beneficiary = beneficiary;

        assembly {
            let bal := selfbalance()

            // (bool sent, ) = payable(beneficiary).call{value: balance}("");
            let sent := call(gas(), _beneficiary, bal, 0, 0, 0, 0)
            if iszero(sent) {
                mstore(0x00, 0x90b8ec1800000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }

            // emit Approved(balance);
            // topic0 = keccak256("Approved(uint256)")
            mstore(0x00, bal)
            log1(
                0x00,
                0x20,
                0x3ad93af63cb7967b23e4fb500b7d7d28b07516325dcf341f88bebf959d82c1cb
            )
        }
    }

    /**
     * @notice Arbiter refunds all funds back to the depositor.
     * @dev Mirrors approve() exactly, but sends to `depositor` and emits
     *      Refunded instead of Approved.
     */
    function refund() external {
        address _arbiter = arbiter;

        assembly {
            if iszero(eq(caller(), _arbiter)) {
                mstore(0x00, 0xccb665a600000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }
            if sload(0) {
                mstore(0x00, 0x6d5703c200000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }

            sstore(0, 1)

            let bal := selfbalance()
            if iszero(bal) {
                mstore(0x00, 0x43f9e11000000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }
        }

        address _depositor = depositor;

        assembly {
            let bal := selfbalance()

            let sent := call(gas(), _depositor, bal, 0, 0, 0, 0)
            if iszero(sent) {
                mstore(0x00, 0x90b8ec1800000000000000000000000000000000000000000000000000000000)
                revert(0x00, 0x04)
            }

            // topic0 = keccak256("Refunded(uint256)")
            mstore(0x00, bal)
            log1(
                0x00,
                0x20,
                0x3d2a04f53164bedf9a8a46353305d6b2d2261410406df3b41f99ce6489dc003c
            )
        }
    }

    /**
     * @notice Returns the contract's current ETH balance.
     */
    function getBalance() external view returns (uint256 bal) {
        assembly {
            bal := selfbalance()
        }
    }
}
